title: Maple
timezone: America/New_York
url: 
description: > #
  A portfolio theme for Jekyll and Siteleaf.
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: post
- scope:
    path: ''
    type: posts
  values:
    permalink: "/:title/"
    layout: post
    image: 
    tags: 
permalink: pretty
exclude:
- Gruntfile.js
- Gemfile.lock
- package.json
- README*
- node_modules
- '.gitignore'
theme: maple
markdown: kramdown
highlighter: rouge
excerpt_separator: |2+



sass:
  style: compressed
repository: 
date_format: '%b %-d, %Y'
